[srv]
hostname = '0.0.0.0'
port = 9101

[srv.auth]
token = ''

[log]
level = 'info'

[db]
type = 'sqlite'

[db.sqlite]
path = '/vol/note/prunus'

# [db.postgres]
# hostname = 'arch.lan'
# port = 5432
# database = 'prunus'
# user = 'postgres'
# password = 'postgres'

[llm]
hostname = 'arch.lan'
port = 1234

[llm.chat]
model = 'qwen3.5-4b'

[llm.embed]
model = 'text-embedding-bge-m3'
# must match model
dimension = 1024

[vault]
path = '/data/note/prunus'

# [search]
# vector_weight = 0.6
# fts_weight = 0.4
# vector_gate = 0.8
# dedup_threshold = 0.85
