[srv]
hostname = '0.0.0.0'
port = 9101

[srv.auth]
token = ''

[log]
level = 'info'

[db]
type = 'sqlite'

[db.sqlite]
path = '/vol/note/prunus'

# [db.postgres]
# hostname = 'arch.lan'
# port = 5432
# database = 'prunus'
# username = 'postgres'
# password = 'postgres'

[llm]
hostname = 'host.lan'
port = 1234

[llm.chat]
model = 'qwen3.5-4b'

[llm.embed]
model = 'text-embedding-bge-m3'
# must match model
dimension = 1024

[cfg]
dir = './cfg'

[grove]
path = '/data/note/prunus'

# [search.dedup]
# threshold = 0.85

# [search.fts]
# weight = 0.4

# [search.vector]
# gate = 0.8
# weight = 0.6
